Зиннуров Н. 2.1.6
NailZinn/dotnet-homeworks-2 pull request #23
Opened 2022-10-23 10:01 UTC by NailZinn

2022-10-23 15:17 UTC, ashenBlade reviewed
Вроде норм

2022-10-23 16:30 UTC, ashenBlade requested changes
ошибки

2022-10-23 16:30 UTC, ashenBlade commented on Homework6/Hw6.Client/Program.fs
> +    Task.Delay(1000) |> ignore
задержки не будет

2022-10-23 16:30 UTC, ashenBlade commented on Homework6/Hw6.Client/Program.fs
> +    let client = new HttpClient()
HttpClient - IDisposable

2022-10-23 16:30 UTC, ashenBlade commented on Homework6/Hw6.Client/Program.fs
> +            printfn $"{input |> getErrorMessage}"
изменить проверку на ошибку

2022-10-23 17:12 UTC, ashenBlade requested changes
Ошибки конкретнее

2022-10-23 17:12 UTC, ashenBlade commented on Homework6/Hw6.Client/Program.fs
> +            :? AggregateException -> return "could not compute the expression. Try again"
Лови конкретные ошибки. ловишь AggregateException - плохо пахнет

2022-10-23 17:26 UTC, NailZinn commented on Homework6/Hw6.Client/Program.fs
> +            :? AggregateException -> return "could not compute the expression. Try again"
Там такой exception выбрасывается при вводе непонятных. Вообще я не особо понимаю, почему там это выскакивает, у меня ведь на беке прописано, что если что-то не спарсилось, то возвращать сообщение об этом. Но почему-то это сообщение не подхватывает клиент

2022-10-23 17:45 UTC, NailZinn commented on Homework6/Hw6.Client/Program.fs
> +            :? AggregateException -> return "could not compute the expression. Try again"
всё исправил

2022-10-23 17:50 UTC, ashenBlade requested changes

2022-10-23 17:50 UTC, ashenBlade commented on Homework6/Hw6.Client/Program.fs
> +            | HttpStatusCode.BadRequest -> response.Content.ReadAsStringAsync() |> Async.AwaitTask
в чем разница?

2022-10-23 17:54 UTC, NailZinn commented on Homework6/Hw6.Client/Program.fs
> +            | HttpStatusCode.BadRequest -> response.Content.ReadAsStringAsync() |> Async.AwaitTask
При badrequest он кидает HttpRequestException, а не выводит сообщение.

2022-10-23 18:25 UTC, ashenBlade requested changes

2022-10-23 18:25 UTC, ashenBlade commented on Homework6/Hw6.Client/Program.fs
> +        return! response.Content.ReadAsStringAsync() |> Async.AwaitTask
нет проверки на результат

2022-10-23 18:27 UTC, NailZinn commented on Homework6/Hw6.Client/Program.fs
> +        return! response.Content.ReadAsStringAsync() |> Async.AwaitTask
А что нужно проверить?

2022-10-24 18:19 UTC, ashenBlade approved these changes

2022-10-24 18:20 UTC, merged