Зиннуров Н. 2.1.7
NailZinn/dotnet-homeworks-2 pull request #24
Opened 2022-10-26 15:41 UTC by NailZinn

2022-10-26 16:17 UTC, ashenBlade requested changes

2022-10-26 16:17 UTC, ashenBlade commented on Homework7/Hw7/Models/UserProfile.cs
> +};
в отдельный файл

2022-10-26 16:17 UTC, ashenBlade commented on Homework7/Hw7/MyHtmlServices/HtmlHelperExtensions.cs
> +        var zip = properties.Zip(displayAttrs);
zip лишний

2022-10-26 16:17 UTC, ashenBlade commented on Homework7/Hw7/MyHtmlServices/HtmlHelperExtensions.cs
> +        foreach (var (property, displayAttribute) in zip)
запихнуть сразу в foreach

2022-10-26 16:17 UTC, ashenBlade commented on Homework7/Hw7/MyHtmlServices/HtmlHelperExtensions.cs
> +    }
нельзя конкатенировать напрямую

2022-10-26 16:17 UTC, ashenBlade commented on Homework7/Hw7/MyHtmlServices/HtmlHelperExtensions.cs
> +using Hw7.Models;
Везде нужно санитизировать HTML. Не конкатенировать/интерполировать строки напрямую

2022-10-26 16:17 UTC, ashenBlade commented on Homework7/Hw7/MyHtmlServices/HtmlHelperExtensions.cs
> +            foreach (var validator in validationAttributes)
а если у свойства нет ValidationAttribute

2022-10-26 16:17 UTC, ashenBlade commented on Homework7/Hw7/MyHtmlServices/HtmlHelperExtensions.cs
> +    }
Не конкатенируй напрямую. И нужно санитизировать HTML перед интерполированием

2022-10-26 16:17 UTC, ashenBlade commented on Homework7/Hw7/MyHtmlServices/HtmlHelperExtensions.cs
> +        return Enumerable
это называется data.Select(d => $"").ToArray();

2022-10-26 16:17 UTC, ashenBlade commented on Homework7/Hw7/MyHtmlServices/HtmlHelperExtensions.cs
> +        => attribute == null ? SplitStringByUpperCase(propertyName) : attribute.Name;
'is' вместо '=='

2022-10-26 16:38 UTC, NailZinn commented on Homework7/Hw7/MyHtmlServices/HtmlHelperExtensions.cs
> +            foreach (var validator in validationAttributes)
Тогда validationAttributes будет пуст и foreach пропустится

2022-10-26 18:12 UTC, ashenBlade approved these changes

2022-10-28 16:17 UTC, ashenBlade approved these changes

2022-10-30 11:34 UTC, merged